### PR TITLE
fix(ui): bugs

### LINKED ISSUE #52: [Bug]: Followers count overreported by 1 on browser
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

Juxtaposition browser (Mobile/PC), overreports the follower count by 1 compared to Nintendo 3DS and Wii U.

### What did you expect to happen?

The correct count as reported from a 3DS or Wii U

### Steps to reproduce?

1. Access an userpage on browser
2. Access an userpage on 3DS or Wii U
3. Compare the follower number, the 3DS and Wii U one has the correct count. (All new accounts start from 0 on 3DS and Wii U, 1 on browser).

### Other relevant information. (OPTIONAL)

_No response_

### LINKED ISSUE #214: [Enhancement]: Mark User Page link in sidebar with "selected" class when on /users/me
### Checked Existing

- [x] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

This is what the link currently looks like when you're on the user page of your profile

Image

On other pages the related link looks like this, it has the "selected" class, but when on your profile the User Page link doesn't have the class.

Image

If you add the "selected" class to the User Page link it looks like this

Image

### Any other details to share? (OPTIONAL)

_No response_

### LINKED ISSUE #264: [Bug]: 404 page title is too wide on 3DS
### Checked Existing

- [x] I have checked the repository for duplicate issues.

### What happened?

The title on the 404 page which appears when going to a non-existent community page is too long to fit on the screen, and lets you scroll to see the blue background.

Image

### What did you expect to happen?

The title is short enough to fit on the page.

### Steps to reproduce?

1. Launch a game with an in-game Miiverse button which sends you to the community of a game that doesn't exist. I tested this with Team Kirby Clash Deluxe - the button is in the Profile tab.
2. Press the button to open the 404 page.
3. Use the dpad/circle pad to scroll the menu sideways.

### Other relevant information. (OPTIONAL)

_No response_

### LINKED ISSUE #349: [Bug]: Juxt Web infinite scroll locks up after 3 loads on Apple WebKit
### Checked Existing

- [x] I have checked the repository for duplicate issues.

### What happened?

If you're on Safari on iOS or Mac, on the third infinite scroll activation the JS locks up and the page stops rendering. CPU usage is pinned at 100%.

https://github.com/user-attachments/assets/94acbe4d-7be5-4f43-84e5-9e1592530008

Image

### What did you expect to happen?

Infinite scroll works normally.

### Steps to reproduce?

1. Open a long feed, like the Global feed
2. Scroll down until you reach the "Load more posts" button.
3. Repeat 2 more times. Then the browser locks up

### Other relevant information. (OPTIONAL)

_No response_

### LINKED ISSUE #436: [Bug]: On Wii U: "All Communities" button appears when on the "All Communities" tab.
### Checked Existing

- [x] I have checked the repository for duplicate issues.

### What happened?

On Juxtaposition's main page, if you click "All Communities", the page is displayed normally, but the "All Communities" button is still there. If you click that button, nothing happens, so it's just a visual thing.

### What did you expect to happen?

I expected for the "All Communities" button to disappear, as I'm already on the "All Communities" page.

### Steps to reproduce?

_No response_

### Other relevant information. (OPTIONAL)

I think that this didn't happen before, because I had never noticed something similar until a few weeks ago.

### LINKED ISSUE #447: [Bug]: Can't Scroll to "Go Back" Button with D-Pad on Wii U Console
### Checked Existing

- [x] I have checked the repository for duplicate issues.

### What happened?

Using the D-Pad when on Juxt Wii U Console can't actually scroll to the "Go Back" button when viewing a post page.

### What did you expect to happen?

To be able to go over the button like every other button.

### Steps to reproduce?

1. Go to a post page.
2. Use the Dpad to scroll down the buttons

### Other relevant information. (OPTIONAL)

_No response_

### PR DESCRIPTION
**Pull request by ashquarky**
Resolves #436
Resolves #447 
Resolves #349 
Resolves #264
Resolves #214 
Resolves #52 

### Changes:

idk man it resolves the bugs listed above

- [x] I have read and agreed to the [Code of Conduct](https://github.com/PretendoNetwork/Pretendo/blob/master/.github/CODE_OF_CONDUCT.md).
- [x] I have read and complied with the [contributing guidelines](https://github.com/PretendoNetwork/Pretendo/blob/master/.github/CONTRIBUTING.md).
- [x] What I'm implementing was an [approved issue](../issues?q=is%3Aopen+is%3Aissue+label%3Aapproved).
- [x] I have tested all of my changes.

### CODE REVIEW

File: apps/juxtaposition-ui/src/services/juxt-web/views/ctr/userPageView.tsx [hunk 1]
```diff
@@ -63,7 +63,7 @@ export function CtrUserPageView(props: UserPageViewProps): ReactNode {
 												<span className="sprite sp-follower-count inline-sprite"></span>
 												<span id="followers">
 													{' '}
-													{props.userContent.following_users.length - 1}
+													{props.userContent.following_users.length}
```
Comment (mrjvs) [inline apps/juxtaposition-ui/src/services/juxt-web/views/ctr/userPageView.tsx:66]: PR #482 also addresses this by accident. but ill deal with the merge conflicts when it comes out of draft

**Review by mrjvs — APPROVED** [review]
